/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pmjaibuokyyrshubokfp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtamFpYnVva3l5cnNodWJva2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjU3NzgsImV4cCI6MjA4ODU0MTc3OH0.7Uc1iUfyVHeM-envDohLYtN72uvgRePEjxLHKUWQNd0"
